export const AUDIT_ACTIONS = {
  organizationCreated: 'ORGANIZATION_CREATED',
  organizationUpdated: 'ORGANIZATION_UPDATED',
  organizationStatusChanged: 'ORGANIZATION_STATUS_CHANGED',
  organizationContextSwitched: 'ORGANIZATION_CONTEXT_SWITCHED',
  memberInvited: 'ORGANIZATION_MEMBER_INVITED',
  invitationCancelled: 'ORGANIZATION_INVITATION_CANCELLED',
  memberAccepted: 'ORGANIZATION_MEMBER_ACCEPTED',
  memberSuspended: 'ORGANIZATION_MEMBER_SUSPENDED',
  memberReactivated: 'ORGANIZATION_MEMBER_REACTIVATED',
  memberRemoved: 'ORGANIZATION_MEMBER_REMOVED',
  memberLeft: 'ORGANIZATION_MEMBER_LEFT',
  roleAssigned: 'ORGANIZATION_ROLE_ASSIGNED',
  roleRemoved: 'ORGANIZATION_ROLE_REMOVED',
  ownershipTransferred: 'ORGANIZATION_OWNERSHIP_TRANSFERRED',
  taxonomyCreated: 'TAXONOMY_ITEM_CREATED',
  taxonomyUpdated: 'TAXONOMY_ITEM_UPDATED',
  taxonomyDeleted: 'TAXONOMY_ITEM_DELETED',
  taxonomyDeactivated: 'TAXONOMY_ITEM_DEACTIVATED',
  providerProfileCreated: 'PROVIDER_PROFILE_CREATED',
  providerProfileUpdated: 'PROVIDER_PROFILE_UPDATED',
  providerCapabilitiesChanged: 'PROVIDER_CAPABILITIES_CHANGED',
  professionalProfileCreated: 'PROFESSIONAL_PROFILE_CREATED',
  professionalProfileUpdated: 'PROFESSIONAL_PROFILE_UPDATED',
  professionalExperienceCreated: 'PROFESSIONAL_EXPERIENCE_CREATED',
  professionalExperienceUpdated: 'PROFESSIONAL_EXPERIENCE_UPDATED',
  professionalExperienceDeleted: 'PROFESSIONAL_EXPERIENCE_DELETED',
} as const;

export const AUDIT_ENTITIES = {
  organization: 'organization',
  organizationMember: 'organization_user',
  organizationMemberRole: 'organization_user_role',
  organizationInvitation: 'organization_invitation',
  serviceCategory: 'service_category',
  service: 'service',
  standard: 'standard',
  industry: 'industry',
  location: 'location',
  providerProfile: 'provider_profile',
  professionalProfile: 'professional_profile',
  professionalExperience: 'professional_experience',
} as const;
