export const SYSTEM_ACCESS_LEVEL_CODES = ['ADMIN', 'CREATOR', 'EDITOR', 'VIEWER'];
export const SYSTEM_ROLE_CODES = [
  'SUPER_ADMIN',
  'ADMIN',
  'BUYER_ADMIN',
  'BUYER_USER',
  'PROVIDER_ADMIN',
  'PROVIDER_USER',
  'PROFESSIONAL',
];
